general_info:
  multi_view: False
  classes : ['background', 'Benign calcification', 'Malignant calcification', 'Benign mass', 'Malignant mass']
  random_seed : 2
  image_source_dir_train : ''
  image_source_dir_val : ''
  image_source_dir_test : ''
  best_weights_path : '/content/drive/MyDrive/BR-Runs/Run3/run/checkpoints'
  activation : 'softmax'
  image_height : 256
  image_width : 256
  image_channels: 3
  train_batch_size : 32
  val_batch_size : 32
  test_batch_size : 32
  patch_model_weight: ''
  patch_training: True
  three_phase_training: False

info_training:
  run : '/content/drive/MyDrive/BR-Runs/TestRun/run'
  export: '/content/drive/MyDrive/BR-Runs/TestRun/export'
  epochs : 1
  initial_learning_rate: 1e-5
  loss : 'categorical_crossentropy'
  export_metric : 'val_accuracy'
  export_mode : 'max'

data_sequence:
  train_csv_file : '../data/train.csv'
  validation_csv_file : '../data/validation.csv'
  test_csv_file : '../data/test.csv'
  x_names : 'imgfile'
  cc_names: ''
  mlo_names: ''
  image_height: 256
  image_width: 256
  image_channels: 3
  augment : False
  verbose : False
  steps : None
  shuffle_on_epoch_end : True
  augmenter: False
  synthesize: False

augmentation:
  rotation_range: 10
  rotation_proba: 0.3
  flip_proba: 0.5

mlflow:
  model_name: ResNet50
  dataset: CBIS_Patches
  training_mode: 'Patch-Classifier | Contrast Enhancement'


evaluation:
  confusion_matrix : True
  classification_report : True
  performance_metrics : True
  precision_recall_curves : True
  auc_curves : True
  wrong_prediction : "positive"
  explainability : True
  eval_saving_path : '/content/drive/MyDrive/BR-Runs/Run3/evaluation.csv'
  saving_dir : '/content/drive/MyDrive/BR-Runs/Run3'


