general_info:
  multi_view: False
  classes : ['background', 'Benign calcification', 'Malignant calcification', 'Benign mass', 'Malignant mass']
  random_seed : 2
  image_source_dir_train : ''
  image_source_dir_val : ''
  image_source_dir_test : ''
  best_weights_path : ''
  activation : 'softmax'
  image_height_whole : 1024
  image_width_whole: 728
  image_height_patch: 256
  image_width_patch: 256
  image_channels: 3
  train_batch_size : 64
  val_batch_size : 64
  test_batch_size : 64
  patch_model_weight: ''
  patch_training: True
  three_phase_training: True

info_training:
  history_output_path : '/content/drive/MyDrive/BR-Runs/Run5/history.csv'
  use_best_weights : False
  output_weights_name : '/content/drive/MyDrive/BR-Runs/Run5/output_model.h5'
  epochs : 10
  initial_learning_rate: 1e-4
  loss : 'categorical_crossentropy'

data_sequence:
  train_csv_file : '../data/train.csv'
  validation_csv_file : '../data/validation.csv'
  test_csv_file : '../data/validation.csv'
  x_names : 'imgfile'
  cc_names: ''
  mlo_names: ''
  target_size_h : 256
  target_size_w : 256
  image_height_whole: 1024
  image_width_whole: 728
  image_height_patch: 256
  image_width_patch: 256
  image_channels: 3
  augment : False
  verbose : False
  steps : None
  shuffle_on_epoch_end : True
  augmenter: False
  synthesize: True

augmentation:
  rotation_range: 10
  rotation_proba: 0.3
  flip_proba: 0.5

evaluation:
  confusion_matrix : True
  classification_report : True
  performance_metrics : True
  precision_recall_curves : True
  auc_curves : True
  wrong_prediction : "positive"
  explainability : True

model_class: model.DenseNet

