general_info:
  multi_view: False
  classes : ['Malignant']
  random_seed : 2
  image_source_dir_train : '../data/'
  image_source_dir_val : '../data/'
  image_source_dir_test : '../data/'
  best_weights_path : ''
  activation : 'sigmoid'
  image_height : 1024
  image_width : 768
  image_channels: 3
  train_batch_size : 4
  val_batch_size : 4
  test_batch_size : 4
  base_model_name: 'densenet121'

info_training:
  run : '/content/drive/MyDrive/BR-Runs/image/benign-malignant/mass/Run1/run'
  export: '/content/drive/MyDrive/BR-Runs/image/mass-calc/benign-malignant/mass/Run1/export'
  epochs : 20
  initial_learning_rate: 1e-4
  loss : 'binary_crossentropy'
  export_metric : 'val_accuracy'
  export_mode : 'max'

data_sequence:
  train_csv_file : '../data/train.csv'
  validation_csv_file : '../data/validation.csv'
  test_csv_file : '../data/test.csv'
  x_names : 'imgfile'
  cc_names: ''
  mlo_names: ''
  image_height: 1024
  image_width: 768
  image_channels: 3
  augment : False
  verbose : False
  steps : None
  shuffle_on_epoch_end : True
  augmenter: False
  synthesize: False

augmentation:
  rotation_range: 10
  rotation_proba: 0.3
  flip_proba: 0.5

mlflow:
  model_name: 'DenseNet121'
  dataset: 'CBIS and DDSM mass Images'
  training_mode: 'CC-Image Classifier | Contrast Enhanced'

data:
  path_to_data_1: '/content/drive/MyDrive/Breast Cancer Preprocessed Datasets/CBIS.zip'
  path_to_data_2: '/content/drive/MyDrive/Breast Cancer Preprocessed Datasets/CMMD.zip'
  path_to_labels_1: '/content/drive/MyDrive/Breast Cancer Preprocessed Datasets/cbis-meta-data.csv'
  path_to_labels_2: '/content/drive/MyDrive/Breast Cancer Preprocessed Datasets/cmmd-meta-data.csv'
  view : 'CC'


evaluation:
  confusion_matrix : True
  classification_report : True
  performance_metrics : True
  precision_recall_curves : True
  auc_curves : True
  wrong_prediction : "positive"
  explainability : True
  eval_saving_path : '/content/drive/MyDrive/BR-Runs/whole/synthesized/Run1/evaluate.csv'
  saving_dir : '/content/drive/MyDrive/BR-Runs/whole/synthesized/Run1'


