general_info:
  multi_view: False
  classes : ['Benign calcification', 'Malignant calcification', 'Benign mass', 'Malignant mass']
  random_seed : 2
  image_source_dir_train : ''
  image_source_dir_val : ''
  image_source_dir_test : ''
  best_weights_path : ''
  activation : 'sigmoid'
  image_height : 1024
  image_width : 768
  image_channels: 3
  train_batch_size : 2
  val_batch_size : 2
  test_batch_size : 2
  patch_model_weight: '/content/drive/MyDrive/BR-Runs/Run3/run/checkpoints'
  patch_training: False
  three_phase_training: False

info_training:
  run : '/content/drive/MyDrive/BR-Runs/whole/clahe/Run1/run'
  export: '/content/drive/MyDrive/BR-Runs/whole/clahe/Run1/export'
  epochs : 1
  initial_learning_rate: 1e-5
  loss : 'binary_crossentropy'
  export_metric : 'val_accuracy'
  export_mode : 'max'

data_sequence:
  train_csv_file : '../data/train.csv'
  validation_csv_file : '../data/validation.csv'
  test_csv_file : '../data/test.csv'
  x_names : 'imgfile'
  cc_names: ''
  mlo_names: ''
  image_height: 1024
  image_width: 768
  image_channels: 3
  augment : False
  verbose : False
  steps : None
  shuffle_on_epoch_end : True
  augmenter: False
  synthesize: False

augmentation:
  rotation_range: 10
  rotation_proba: 0.3
  flip_proba: 0.5

mlflow:
  model_name: 'ResNet50-Extended'
  dataset: 'CBIS and DDSM'
  training_mode: 'CC-Image Classifier | Contrast Enhancement'

data:
  path_to_data_1: '/content/drive/MyDrive/Breast Cancer Preprocessed Data/CBIS.zip'
  path_to_data_2: '/content/drive/MyDrive/Breast Cancer Preprocessed Data/CMMD.zip'
  path_to_labels_1: '/content/drive/MyDrive/Breast Cancer Preprocessed Data/cbis-meta-data.csv'
  path_to_labels_2: '/content/drive/MyDrive/Breast Cancer Preprocessed Data/cmmd-meta-data.csv'
  view : 'CC'


evaluation:
  confusion_matrix : True
  classification_report : True
  performance_metrics : True
  precision_recall_curves : True
  auc_curves : True
  wrong_prediction : "positive"
  explainability : True
  eval_saving_path : '/content/drive/MyDrive/BR-Runs/whole/clahe/Run1/evaluate.csv'
  saving_dir : '/content/drive/MyDrive/BR-Runs/whole/clahe/Run1'


